const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
const FETCH_PROMOTIONS = 'FETCH_PROMOTIONS';
const FETCH_PROMOTION = 'FETCH_PROMOTION';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const FETCH_SIMILAR_PRODUCTS = 'FETCH_SIMILAR_PRODUCTS';
const FETCH_PRODUCT = 'FETCH_PRODUCT';
const POST_RATING = 'POST_RATING';
const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
const FETCH_CART = 'FETCH_CART';
const POST_CART_PRODUCT = 'POST_CART_PRODUCT';
const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT';

export {
  LOGIN,
  LOGOUT,
  FETCH_CURRENT_USER,
  FETCH_PROMOTIONS,
  FETCH_PROMOTION,
  FETCH_PRODUCTS,
  FETCH_SIMILAR_PRODUCTS,
  FETCH_PRODUCT,
  POST_RATING,
  FETCH_CATEGORIES,
  FETCH_CART,
  POST_CART_PRODUCT,
  DELETE_CART_PRODUCT,
};
