const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
const FETCH_PROMOTIONS = 'FETCH_PROMOTIONS';
const FETCH_PROMOTION = 'FETCH_PROMOTION';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const FETCH_PRODUCT = 'FETCH_PRODUCT';
const POST_RATING = 'POST_RATING';

export {
  LOGIN,
  LOGOUT,
  FETCH_CURRENT_USER,
  FETCH_PROMOTIONS,
  FETCH_PROMOTION,
  FETCH_PRODUCTS,
  FETCH_PRODUCT,
  POST_RATING,
};
