const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
const FETCH_PROMOTIONS = 'FETCH_PROMOTIONS';
const FETCH_PROMOTION = 'FETCH_PROMOTION';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export {
  LOGIN,
  LOGOUT,
  FETCH_CURRENT_USER,
  FETCH_PROMOTIONS,
  FETCH_PROMOTION,
  FETCH_PRODUCTS,
};
