const GET_PROMOTIONS = 'GET_PROMOTIONS';
const GET_PROMOTIONS_LOADING = 'IS_PROMOTIONS_LOADING';
const GET_PROMOTIONS_ERROR = 'GET_PROMOTIONS_ERROR';
const GET_PROMOTION = 'GET_PROMOTION';

export {
  GET_PROMOTIONS,
  GET_PROMOTIONS_LOADING,
  GET_PROMOTIONS_ERROR,
  GET_PROMOTION,
};
