const GET_CURRENT_USER = 'GET_CURRENT_USER';
const GET_CURRENT_USER_LOADING = 'GET_CURRENT_USER_LOADING';
const GET_PROMOTIONS_LIST = 'GET_PROMOTIONS_LIST';
const GET_PROMOTIONS_BY_ID = 'GET_PROMOTIONS_BY_ID';
const GET_PROMOTIONS_LOADING = 'GET_PROMOTIONS_LOADING';
const GET_PROMOTIONS_ERROR = 'GET_PROMOTIONS_ERROR';
const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
const GET_PROMOTION_DATA = 'GET_PROMOTION_DATA';
const GET_PROMOTION_LOADING = 'GET_PROMOTION_LOADING';
const GET_PROMOTION_ERROR = 'GET_PROMOTION_ERROR';

export {
  GET_CURRENT_USER,
  GET_CURRENT_USER_LOADING,
  GET_PROMOTIONS_LIST,
  GET_PROMOTIONS_BY_ID,
  GET_PROMOTIONS_LOADING,
  GET_PROMOTIONS_ERROR,
  GET_PROMOTION_DATA,
  GET_PROMOTION_LOADING,
  GET_PROMOTION_ERROR,
  GET_PRODUCTS_LIST,
  GET_PRODUCTS_LOADING,
  GET_PRODUCTS_ERROR,
};
