const SET_PROMOTIONS = 'SET_PROMOTIONS';
const SET_PROMOTIONS_ERROR = 'SET_PROMOTIONS_ERROR';
const SET_PROMOTIONS_LOADING = 'SET_PROMOTIONS_LOADING';

export {
  SET_PROMOTIONS,
  SET_PROMOTIONS_LOADING,
  SET_PROMOTIONS_ERROR,
};
