const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SET_PROMOTIONS_LIST = 'SET_PROMOTIONS_LIST';
const SET_PROMOTIONS_LOADING = 'SET_PROMOTIONS_LOADING';
const SET_PROMOTIONS_ERROR = 'SET_PROMOTIONS_ERROR';
const SET_PROMOTION_DATA = 'SET_PROMOTION_DATA';
const SET_PROMOTION_ID = 'SET_PROMOTION_ID';
const SET_PROMOTION_LOADING = 'SET_PROMOTION_LOADING';
const SET_PROMOTION_ERROR = 'SET_PROMOTION_ERROR';
const SET_PRODUCTS_LIST = 'SET_PRODUCTS_LIST';
const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
const SET_PRODUCTS_ERROR = 'SET_PRODUCTS_ERROR';

export {
  SET_CURRENT_USER,
  SET_PROMOTIONS_LIST,
  SET_PROMOTIONS_LOADING,
  SET_PROMOTIONS_ERROR,
  SET_PROMOTION_DATA,
  SET_PROMOTION_ID,
  SET_PROMOTION_LOADING,
  SET_PROMOTION_ERROR,
  SET_PRODUCTS_LIST,
  SET_PRODUCTS_LOADING,
  SET_PRODUCTS_ERROR,
};
